# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  gh-hosted-integration-test:
    strategy:
      fail-fast: false
      matrix:
        groups: ${{ fromJSON(needs.gh-hosted-collect-integration-tests.outputs.groups) }}
        ubuntu-versions:
          # Update whenever charmcraft.yaml is changed
          - series: focal
            bases-index: 0
          - series: jammy
            bases-index: 1
        juju-snap-channel:  ["3.6/stable"]
        new-wait-for-idle: ["True", "False"]
        exclude:
          - groups: {path_to_test_file: tests/integration/test_data_integrator.py}
            ubuntu-versions: {series: focal}
          - groups: {path_to_test_file: tests/integration/test_hacluster.py}
            ubuntu-versions: {series: focal}
    name: ${{ matrix.juju-snap-channel }} - (GH hosted) ${{ matrix.groups.job_name }} | ${{ matrix.ubuntu-versions.series }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 3.6.0"
          juju-channel: ${{ matrix.juju-snap-channel }}
      # pattern: ${{ needs.build.outputs.artifact-prefix }}-*
      - name: Run integration tests
        run: tox run -e integration -- "${{ matrix.groups.path_to_test_file }}" -m "not unstable" --mysql-router-charm-series=${{ matrix.ubuntu-versions.series }} --mysql-router-charm-bases-index=${{ matrix.ubuntu-versions.bases-index }}
        env:
          JUJU_NEW_WAIT_FOR_IDLE: ${{ matrix.new-wait-for-idle }}
          LIBJUJU_VERSION_SPECIFIER: 3.6.0
          SECRETS_FROM_GITHUB: |
            {
              "UBUNTU_PRO_TOKEN" : "${{ secrets.UBUNTU_PRO_TOKEN }}",
              "LANDSCAPE_ACCOUNT_NAME": "${{ secrets.LANDSCAPE_ACCOUNT_NAME }}",
              "LANDSCAPE_REGISTRATION_KEY": "${{ secrets.LANDSCAPE_REGISTRATION_KEY }}",
            }
